# Generated by Django 5.0rc1 on 2023-12-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('apos', models.TextField()),
                ('ipcs', models.TextField()),
                ('featurewords', models.TextField()),
                ('probs', models.TextField()),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
