# Generated by Django 5.0rc1 on 2024-01-14 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patent_api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_word", models.CharField(max_length=255)),
                ("distribution_conclusion", models.TextField()),
                ("innovation_conclusion", models.TextField()),
                ("network_conclusion", models.TextField()),
                ("wordcloud_base64", models.TextField()),
                ("word_network_base64", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "search_word")},
            },
        ),
    ]
