# Generated by Django 5.0rc1 on 2024-01-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patent_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("search_word", models.CharField(max_length=255)),
                ("distribution_conclusion", models.TextField()),
                ("innovation_conclusion", models.TextField()),
                ("network_conclusion", models.TextField()),
                ("wordcloud_base64", models.TextField()),
                ("word_network_base64", models.TextField()),
            ],
        ),
    ]
