# Generated by Django 5.0rc1 on 2024-01-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_api', '0002_usersearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearch',
            name='distribution_conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='innovation_conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='network_conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='word_network_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='wordcloud_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
