# Generated by Django 5.0rc1 on 2024-01-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_api', '0003_alter_usersearch_distribution_conclusion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearch',
            name='word_network_base64',
        ),
        migrations.RemoveField(
            model_name='usersearch',
            name='wordcloud_base64',
        ),
        migrations.AddField(
            model_name='usersearch',
            name='word_network_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersearch',
            name='wordcloud_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
