# Generated by Django 5.0rc1 on 2024-01-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_api', '0004_remove_usersearch_word_network_base64_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearch',
            name='word_network_image_path',
        ),
        migrations.RemoveField(
            model_name='usersearch',
            name='wordcloud_image_path',
        ),
        migrations.AddField(
            model_name='usersearch',
            name='word_network_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersearch',
            name='wordcloud_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
